name: FontAwesome
options:
  bundleIdPrefix: com.alexusbergo
  deploymentTarget:
    iOS: "8.0"
targets:
  FontAwesome:
    platform: iOS
    scheme: {} # Generate default scheme
    settings:
      GCC_GENERATE_DEBUGGING_SYMBOLS: NO # Avoid downstream warning: "Redistributable static libraries should never be built with module debugging enabled"
      MACH_O_TYPE: staticlib
      MODULEMAP_FILE: FontAwesome/FontAwesome.modulemap
    sources:
      - path: FontAwesome
        excludes:
          - FontAwesome.modulemap
    type: framework
