name: FontAwesome
options:
  bundleIdPrefix: com.alexusbergo
  deploymentTarget:
    iOS: "8.0"
targets:
  FontAwesome:
    info:
      path: Info.plist
    platform: iOS
    scheme: {} # Generate default scheme
    settings:
      MODULEMAP_FILE: FontAwesome.modulemap
    sources:
      - path: .
        excludes:
          - .git
          - .gitignore
          - .gitmodules
          - Demo
          - FontAwesome.modulemap
          - FontAwesome.xcodeproj
          - FontAwesome+iOS.podspec
          - project.yml
          - README.md
          - Resources/fontawesome-github.jpg
    type: framework
